name: Validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      - name: Run repo validation
        run: mise run ci
      - name: Validate OCI artifact packaging
        run: mise run artifact:check
